# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: TransportMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='TransportMessage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16TransportMessage.proto\x1a\x19google/protobuf/any.proto\"\x8f\x01\n\x10TransportMessage\x12\n\n\x02Id\x18\x01 \x01(\x03\x12\x13\n\x0b\x41\x63\x63\x65ssToken\x18\x02 \x01(\t\x12\x1d\n\x07MsgType\x18\x03 \x01(\x0e\x32\x0c.EnumMsgType\x12%\n\x07\x43ontent\x18\x04 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x14\n\x0cRefMessageId\x18\x05 \x01(\x03*j\n\x0b\x45numMsgType\x12\x0e\n\nUnknownMsg\x10\x00\x12\x11\n\x0cHeartBeatReq\x10\xe9\x07\x12\x13\n\x0eMsgReceivedAck\x10\xea\x07\x12\n\n\x05\x45rror\x10\xeb\x07\x12\x17\n\x12WeChatOnlineNotice\x10\xfc\x07\x62\x06proto3')
  ,
  dependencies=[google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])

_ENUMMSGTYPE = _descriptor.EnumDescriptor(
  name='EnumMsgType',
  full_name='EnumMsgType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UnknownMsg', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='HeartBeatReq', index=1, number=1001,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MsgReceivedAck', index=2, number=1002,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Error', index=3, number=1003,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WeChatOnlineNotice', index=4, number=1020,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=199,
  serialized_end=305,
)
_sym_db.RegisterEnumDescriptor(_ENUMMSGTYPE)

EnumMsgType = enum_type_wrapper.EnumTypeWrapper(_ENUMMSGTYPE)
UnknownMsg = 0
HeartBeatReq = 1001
MsgReceivedAck = 1002
Error = 1003
WeChatOnlineNotice = 1020



_TRANSPORTMESSAGE = _descriptor.Descriptor(
  name='TransportMessage',
  full_name='TransportMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='TransportMessage.Id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='AccessToken', full_name='TransportMessage.AccessToken', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='MsgType', full_name='TransportMessage.MsgType', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Content', full_name='TransportMessage.Content', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='RefMessageId', full_name='TransportMessage.RefMessageId', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=197,
)

_TRANSPORTMESSAGE.fields_by_name['MsgType'].enum_type = _ENUMMSGTYPE
_TRANSPORTMESSAGE.fields_by_name['Content'].message_type = google_dot_protobuf_dot_any__pb2._ANY
DESCRIPTOR.message_types_by_name['TransportMessage'] = _TRANSPORTMESSAGE
DESCRIPTOR.enum_types_by_name['EnumMsgType'] = _ENUMMSGTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TransportMessage = _reflection.GeneratedProtocolMessageType('TransportMessage', (_message.Message,), dict(
  DESCRIPTOR = _TRANSPORTMESSAGE,
  __module__ = 'TransportMessage_pb2'
  # @@protoc_insertion_point(class_scope:TransportMessage)
  ))
_sym_db.RegisterMessage(TransportMessage)


# @@protoc_insertion_point(module_scope)
