# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WeChatOnlineNoticeMessage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import TransportMessage_pb2 as TransportMessage__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='WeChatOnlineNoticeMessage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x1fWeChatOnlineNoticeMessage.proto\x1a\x16TransportMessage.proto\"d\n\x19WeChatOnlineNoticeMessage\x12\x10\n\x08WeChatId\x18\x01 \x01(\t\x12\x10\n\x08WeChatNo\x18\x02 \x01(\t\x12\x12\n\nWeChatNick\x18\x03 \x01(\t\x12\x0f\n\x07\x43ountry\x18\x05 \x01(\tb\x06proto3')
  ,
  dependencies=[TransportMessage__pb2.DESCRIPTOR,])




_WECHATONLINENOTICEMESSAGE = _descriptor.Descriptor(
  name='WeChatOnlineNoticeMessage',
  full_name='WeChatOnlineNoticeMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='WeChatId', full_name='WeChatOnlineNoticeMessage.WeChatId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WeChatNo', full_name='WeChatOnlineNoticeMessage.WeChatNo', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='WeChatNick', full_name='WeChatOnlineNoticeMessage.WeChatNick', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Country', full_name='WeChatOnlineNoticeMessage.Country', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['WeChatOnlineNoticeMessage'] = _WECHATONLINENOTICEMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

WeChatOnlineNoticeMessage = _reflection.GeneratedProtocolMessageType('WeChatOnlineNoticeMessage', (_message.Message,), dict(
  DESCRIPTOR = _WECHATONLINENOTICEMESSAGE,
  __module__ = 'WeChatOnlineNoticeMessage_pb2'
  # @@protoc_insertion_point(class_scope:WeChatOnlineNoticeMessage)
  ))
_sym_db.RegisterMessage(WeChatOnlineNoticeMessage)


# @@protoc_insertion_point(module_scope)
